name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.19, 1.20, 1.21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Install reviewdog
      uses: reviewdog/action-install@v1

    - name: Run golint with reviewdog
      run: golint ./... | reviewdog -f=golint -reporter=github-pr-review -filter-mode=nofilter -level=error
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
